# Практические задания к теме №1: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

## Возможности модуля numpy

In [ ]:
import numpy as np

### Задание 1

Создать двумерный массив 3x3 со значениями от 0 до 8

In [ ]:
array_2d = np.arange(9).reshape((3, 3))
array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Задание 2

Создать случайный вектор размера 10 и найти среднее значение всех элементов. Задать значение seed как 42.



In [ ]:
# Установка seed для воспроизведения результатов
np.random.seed(42)

# Создание случайного вектора размера 10
random_vector = np.random.rand(10)

# Нахождение среднего значения всех элементов
mean_value = np.mean(random_vector)

# Выведем полученный выше случайный вектор
random_vector

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
# Выведем среднее значение
mean_value

0.5201367359526748

## Операции над векторами и матрицами в NumPy

### Задание 1

Создать вектор размера 5 со значениями от 0 до 1, включая оба значения.


In [ ]:
# Выведем 5 значений с равным промежутком между ними
vector = np.linspace(0, 1, 5)
vector

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Задание 2

Преобразовать произвольный массив из float в int.

In [ ]:
# Произвольный массив float
float_array = np.array([1.5, 2.7, 3.2, 4.8, 5.1])

# Преобразование в int
int_array = float_array.astype(int)

print(float_array)

[1.5 2.7 3.2 4.8 5.1]


In [ ]:
print(int_array)

[1 2 3 4 5]


## Индексация в массивах

### Задание 1

Поменять 2 строки в произвольном массиве

In [ ]:
# Создание произвольного двумерного массива
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Поменять местами строки 1 и 2
array[1], array[2] = array[2].copy(), array[1].copy()
print(array)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


### Задание 2

Создать массив 9х9, в котором все значения равны 1, кроме тех, которые находятся по краям, они должны быть равны 0 ("рамка из нулей")

In [ ]:
# Создание массива 9x9, заполненного единицами
array = np.ones((9, 9), dtype=int)

# Установка значений по краям равными 0
array[:, [0, -1]] = 0  # Установка значений в первом и последнем столбце
array[[0, -1], :] = 0  # Установка значений в первой и последней строке
print(array)

[[0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0]]
