# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [ ]:
import numpy as np

### Задание 1

**Условие**: Создать 12x12 единичную матрицу (с единицами по диагонали)

1) Выполним задание так, как мы выполняли бы его без использования модуля `NumPy` и выведем время, затраченное на выполнение, введя в начале програмного кода команду `%%timeit`:

In [ ]:
%%timeit
# Создаем 12x12 единичную матрицу
matrix = []
matrix_size = 12


for i in range(matrix_size):
    row = []
    for j in range(matrix_size):
        if i == j:
            row.append(1)
        else:
            row.append(0)
    matrix.append(row)

matrix

18.7 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


*такой вариант решения возможен, однако, он занимает слишком много времени компиляции

2) Воспользуемся модулем `NumPy`:

In [ ]:
%%timeit
matrix = np.zeros((12, 12), dtype=int)  # Создаем матрицу из нулей
for i in range(12):
    matrix[i, i] = 1  # Устанавливаем единицы по диагонали

2.99 µs ± 405 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
matrix

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

3) Теперь в качестве реализации воспользуемся модулем `NumPy`, взяв за основу метод `np.eye`, который создаёт прямоугольную таблицу. Он выглядит следующим образом:
```
np.eye(N, M=None, k=0, dtype=float)
```
Здесь:

* N: количество строк (и столбцов) в матрице.

* M: (по умолчанию M=None) количество столбцов в матрице. Если не указано, то M принимает значение N.

* k: (по умолчанию k=0) смещение главной диагонали. Положительные значения смещают диагональ вверх, отрицательные - вниз.

* dtype: тип данных элементов в матрице.

In [ ]:
%%timeit
matrix = np.eye(12)
dtype = int # по умолчанию используется float и числа будут выводиться с точкой

2.23 µs ± 67.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
matrix

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

4) Теперь решим задачу, воспользовавшись методом `identity`. Его отличие от `eye` заключается в том, что он предназначен для создания именно квадратных матриц. Этот метод выглядит следующим образом:
```
numpy.identity(n, dtype=None)
```
* n: размер квадратной матрицы (количество строк и столбцов).

* dtype: тип данных элементов матрицы (по умолчанию None, что означает использование типа данных по умолчанию).

In [ ]:
%%timeit
matrix = np.identity(12)

3.18 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
matrix

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

Как видим, использование `NumPy` значительно ускоряет процесс работы, что поможет при созхдании больших проектов, где количесто фрагментов кода с вычислениями может достигать больших размеров

### Задание 2 *

**Условие**: Создать 9x9 матрицу и заполнить её в шахматном порядке

1) Стандартный вариант реализации через `NumPy`

In [ ]:
# Создаем матрицу 9x9, заполненную нулями
chess_matrix = np.zeros((9, 9), dtype=int)

# Заполняем матрицу в шахматном порядке
chess_matrix[1::2, ::2] = 1  # Нечетные строки, четные столбцы
chess_matrix[::2, 1::2] = 1  # Четные строки, нечетные столбцы

chess_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

Посмотрим количество времени, потраченное на выполнение задачи ланным способом:

In [ ]:
%%timeit
chess_matrix = np.zeros((9, 9), dtype=int)

chess_matrix[1::2, ::2] = 1
chess_matrix[::2, 1::2] = 1

2.18 µs ± 545 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


2) Релизация с использованием шаблонов

При изучении `NumPy` нашёл достаточно интересный метод `np.tile`. Его особенность в том, что он создаёт массив, повторяя заданный шаблон по указанным осям. Выглядит он следующим образом:
```
numpy.tile(A, reps)

```
* A: Шаблон, который хотим повторить.
* reps: Количество повторений по каждой из оригинальных осей. Это может быть целым числом или кортежем целых чисел, как в случае решения этой задачи.

In [ ]:
matrix = np.tile([[0, 1], [1, 0]], (5, 5))

matrix

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

Однако, у этого метода оказался один существенный минус - время компиляции, чтои может быть плохо при написании объёмного кода:

In [ ]:
%%timeit
matrix = np.tile([[0, 1], [1, 0]], (5, 5))

6.22 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Задание 3

**Условие**: Отсортировать произвольный вектор в порядке возрастания.

In [ ]:
# Создание произвольного вектора со значениями от 0 до 1
np.random.seed(42) # Устанавливаем начальное состояние генератора случайных чисел
vector = np.random.random(10)

vector

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

*не очень понял зачем в коде, уоторый был указан в задании задавать `np.random.seed(42)`, если задание заключается в том, чтобы отсортировать произвольный вектор, в то время как `np.random.seed(42)` при каждом запуске программы будет производить одинаковую последовательность случайных чисел. РАзве что, для удобства проверки и отладки

Для реализации воспольщзуемся методом `np.sort()`, который выглядит следующим образом:
```
numpy.sort(a, axis=-1, kind='quicksort', order=None)

```
* a: Входной массив для сортировки.
* axis: Ось, по которой производится сортировка (по умолчанию -1, что означает сортировку по последней оси).
* kind: Алгоритм сортировки. По умолчанию используется быстрая сортировка ('quicksort'), но также можно выбрать 'mergesort' или 'heapsort'.
* order: Если входной массив состоит из структурных типов данных, вы можете указать поле (или последовательность полей), по которому будет производиться сортировка.

In [ ]:
sorted_vector = np.sort(vector)

sorted_vector

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.60111501, 0.70807258, 0.73199394, 0.86617615, 0.95071431])

### Задание 4

**Условие**: Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [ ]:
min_value = 3
max_value = 5
colomns = 8
rows = 3

fourth_array = np.random.randint(min_value, max_value,(colomns, rows))

fourth_array

array([[3, 4, 3],
       [4, 4, 4],
       [3, 4, 3],
       [4, 3, 4],
       [3, 3, 4],
       [3, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

Воспользуемся методом `np.all`, который будет применяться по оси 1, т. е. производить поиск по строкам (`axis=1`) и принимать значение True только в том случае, если все элементы этой оси (строки) равны 4. Поместим эту конструкцию дополнительно в метод `np.where`, который выведет индексы строк, в которых было получено True (нумерацию индексов строк установил начиная с 1 для удобства)

In [ ]:
# Определяим индексы строк, где все значения равны 4
matching_rows_indices = np.where(np.all(fourth_array == 4, axis=1))[0]

# Выведем индексы строк
if matching_rows_indices.size > 0:
    print("Индексы строк, в которых все значения равны 4:")
    print(matching_rows_indices+1) # выводим индексы строк с True начиная с 1
else:
    print("Нет строк, в которых все значения равны 4.")

Индексы строк, в которых все значения равны 4:
[2 7 8]


### Задание 5

**Условие**: Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

При реализации воспользуемся возможностью NumPy обращаться к последнему элементу массива, вводя в качестве торого индекса `array[-1]`:

In [ ]:
import numpy as np

# Создаем массив из 6 элементов
my_array = np.zeros(6, dtype = int)

# Устанавливаем последний элемент равным 1
my_array[-1] = 1

my_array

array([0, 0, 0, 0, 0, 1])

### Задание 6

**Условие**: Укажите индекс 9 элемента в массиве 2х3х2

Создадим трёхмерный массив размером 2x3x2, котрый будет заполнен числами типа int со значениеми от 0 до 9:

In [ ]:
my_array = np.random.randint(0, 10, size=(2, 3, 2))
my_array

array([[[5, 6],
        [4, 0],
        [0, 2]],

       [[1, 4],
        [9, 5],
        [6, 3]]])

Для того, чтобы вывести индекс 9го элемента массива воспользуемся методом `np.unravel_index()`, который преобразует линейные индексы или массив линейных индексов в индексы соответствующих элементов в многомерном массиве:
```
np.unravel_index(indices, shape, order='C')
```
* indices: Линейные индексы (или массив линейных индексов), которые нужно преобразовать.
* shape: Форма (размеры) многомерного массива, в котором нужно найти линейные индексы (вывод индексов с помощью картежа).
* order: Порядок интерпретации индексов. 'C' для использования порядка C (по умолчанию), 'F' для использования порядка Fortran.

In [ ]:
value = my_array.flat[9]
indices = np.unravel_index(9, my_array.shape)

print("Значение 9-го элемента:", value)
print("Индексы 9-го элемента:", indices)

Значение 9-го элемента: 5
Индексы 9-го элемента: (1, 1, 1)
